services:
  bankingaccountapi:
    image: bankingaccountapi
    build:
      context: .
      dockerfile: BankingAccountApi/Dockerfile
    ports: 
      - "4040:8080"
      - "5040:8081"
    volumes:
      - ./Infrastructure/Database:/Database
    
  transactionapi:
    image: transactionapi
    build:
      context: .
      dockerfile: TransactionApi/Dockerfile
    ports:
      - "4041:8080"
      - "5041:8081"
    volumes:
    - ./Infrastructure/Database:/Database
     
