services:
  bankingaccountapi:
    image: bankingaccountapi
    build:
      context: .
      dockerfile: BankingAccountApi/Dockerfile

  transactionapi:
    image: transactionapi
    build:
      context: .
      dockerfile: TransactionApi/Dockerfile
